# Filename: gcp-network-k8s-labels.yaml

# --- GCP VPC Network ---
apiVersion: compute.gcp.upbound.io/v1beta1 # Network API version
kind: Network
metadata:
  name: zia-build-infra-nw-1
  # --- ADDED K8S LABELS ---
  labels:
    createdby: crossplane
    project: zia-build-infra
    owner: zia-sre
  # -----------------------
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingMode: REGIONAL
    deleteDefaultRoutesOnCreate: false
    # No 'labels:' block here
  providerConfigRef:
    name: default

---
# --- Public Subnets ---

apiVersion: compute.gcp.upbound.io/v1beta1 # Subnetwork API version
kind: Subnetwork
metadata:
  name: zia-build-infra-public-subnet-1
  # --- ADDED K8S LABELS ---
  labels:
    createdby: crossplane
    project: zia-build-infra
    owner: zia-sre
  # -----------------------
spec:
  forProvider:
    ipCidrRange: 172.16.0.0/24
    region: us-west1
    networkRef:
      name: zia-build-infra-nw-1
    # No 'labels:' block here
  providerConfigRef:
    name: default

---
apiVersion: compute.gcp.upbound.io/v1beta1 # Subnetwork API version
kind: Subnetwork
metadata:
  name: zia-build-infra-public-subnet-2
  # --- ADDED K8S LABELS ---
  labels:
    createdby: crossplane
    project: zia-build-infra
    owner: zia-sre
  # -----------------------
spec:
  forProvider:
    ipCidrRange: 172.16.1.0/24
    region: us-west1
    networkRef:
      name: zia-build-infra-nw-1
    # No 'labels:' block here
  providerConfigRef:
    name: default

---
apiVersion: compute.gcp.upbound.io/v1beta1 # Subnetwork API version
kind: Subnetwork
metadata:
  name: zia-build-infra-public-subnet-3
  # --- ADDED K8S LABELS ---
  labels:
    createdby: crossplane
    project: zia-build-infra
    owner: zia-sre
  # -----------------------
spec:
  forProvider:
    ipCidrRange: 172.16.2.0/24
    region: us-west1
    networkRef:
      name: zia-build-infra-nw-1
    # No 'labels:' block here
  providerConfigRef:
    name: default

---
# --- Private Subnets ---

apiVersion: compute.gcp.upbound.io/v1beta1 # Subnetwork API version
kind: Subnetwork
metadata:
  name: zia-build-infra-private-subnet-1
  # --- ADDED K8S LABELS ---
  labels:
    createdby: crossplane
    project: zia-build-infra
    owner: zia-sre
  # -----------------------
spec:
  forProvider:
    ipCidrRange: 172.16.3.0/24
    region: us-west1
    networkRef:
      name: zia-build-infra-nw-1
    privateIpGoogleAccess: true
    # No 'labels:' block here
  providerConfigRef:
    name: default

---
apiVersion: compute.gcp.upbound.io/v1beta1 # Subnetwork API version
kind: Subnetwork
metadata:
  name: zia-build-infra-private-subnet-2
  # --- ADDED K8S LABELS ---
  labels:
    createdby: crossplane
    project: zia-build-infra
    owner: zia-sre
  # -----------------------
spec:
  forProvider:
    ipCidrRange: 172.16.4.0/24
    region: us-west1
    networkRef:
      name: zia-build-infra-nw-1
    privateIpGoogleAccess: true
    # No 'labels:' block here
  providerConfigRef:
    name: default

---
apiVersion: compute.gcp.upbound.io/v1beta1 # Subnetwork API version
kind: Subnetwork
metadata:
  name: zia-build-infra-private-subnet-3
  # --- ADDED K8S LABELS ---
  labels:
    createdby: crossplane
    project: zia-build-infra
    owner: zia-sre
  # -----------------------
spec:
  forProvider:
    ipCidrRange: 172.16.5.0/24
    region: us-west1
    networkRef:
      name: zia-build-infra-nw-1
    privateIpGoogleAccess: true
    # No 'labels:' block here
  providerConfigRef:
    name: default

---
# --- Cloud Router (Required for Cloud NAT) ---
apiVersion: compute.gcp.upbound.io/v1beta2 # Keep v1beta2 as needed before
kind: Router
metadata:
  name: zia-build-infra-nat-router
  labels: # Kubernetes metadata labels
    createdby: crossplane
    project: zia-build-infra
    owner: zia-sre
spec:
  forProvider:
    region: us-west1
    networkRef:
      name: zia-build-infra-nw-1
    bgp:
      asn: 64514 # Keep the ASN
      advertiseMode: DEFAULT # Keep the mode
      # advertisedIpRanges: # <<< REMOVED THIS ENTIRE BLOCK
      #   - range: 1.2.3.4/32
      #     description: "dummy-advertised-range"
  providerConfigRef:
    name: default

---
# --- Cloud NAT Gateway for Private Subnets ---
apiVersion: compute.gcp.upbound.io/v1beta2 # Keep v1beta2 as needed before
kind: RouterNAT
metadata:
  name: zia-build-infra-nat-gateway
  labels: # Kubernetes metadata labels
    createdby: crossplane
    project: zia-build-infra
    owner: zia-sre
spec:
  forProvider:
    routerRef:
      name: zia-build-infra-nat-router
    region: us-west1
    # This specifies the overall mode: we are providing a list of subnets below
    sourceSubnetworkIpRangesToNat: LIST_OF_SUBNETWORKS
    # Now, for each subnet in the list, specify which ranges to NAT
    subnetwork:
      - nameRef:
          name: zia-build-infra-private-subnet-1
        # Specify which IP ranges from this subnet should be NATed
        sourceIpRangesToNat: ["ALL_IP_RANGES"] # <<< ADDED THIS LINE
      - nameRef:
          name: zia-build-infra-private-subnet-2
        # Specify which IP ranges from this subnet should be NATed
        sourceIpRangesToNat: ["ALL_IP_RANGES"] # <<< ADDED THIS LINE
      - nameRef:
          name: zia-build-infra-private-subnet-3
        # Specify which IP ranges from this subnet should be NATed
        sourceIpRangesToNat: ["ALL_IP_RANGES"] # <<< ADDED THIS LINE
    natIpAllocateOption: AUTO_ONLY
    logConfig:
      enable: true
      filter: ERRORS_ONLY
  providerConfigRef:
    name: default